# Test generated by RoostGPT for test python-test-23 using AI Type Azure Open AI and AI Model roost-gpt4-32k

import unittest
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from app import vectorize

class TestVectorize(unittest.TestCase):

    def test_Vectorize_7fb4bc6614(self):
        self.vectorizer = TfidfVectorizer()

        text1 = ["The quick brown fox jumps over the lazy dog"]
        result1 = self.vectorizer.fit_transform(text1).toarray()
        self.assertTrue(np.array_equal(vectorize(text1), result1))

        text2 = ["The", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog"]
        result2 = self.vectorizer.fit_transform(text2).toarray()
        self.assertTrue(np.array_equal(vectorize(text2), result2))

    def test_Vectorize_error(self):
        with self.assertRaises(TypeError):
            vectorize(123)  # attempting to vectorize a non-string type

        with self.assertRaises(ValueError):
            vectorize([])  # attempting to vectorize an empty list

if __name__ == '__main__':
    unittest.main()
